In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
data=pd.read_csv('D://collabGargiMaam//survey_animalHealth//labelEnc//finalData.csv')
data.head()
data.shape

Fever  Diarrhoea  Leftover concentrate  Leftover roughage  feedsource  \
0      0          0                     2                  2           0   
1      1          1                     0                  0           1   
2      0          0                     2                  2           2   
3      1          1                     0                  2           0   
4      1          1                     2                  2           0   

   Manger edge   WasteWaterdisposal  drain_lining  Dung disposal  Floor type  \
0            0                    0             1              1           3   
1            1                    1             0              1           0   
2            0                    1             2              1           4   
3            0                    0             0              0           0   
4            1                    0             0              0           4   

   Cleaning agent  Ventilation level   Housing system   label  
0               8                  2                 0      0  
1               8                  0                 2      0  
2               8                  0                 2      0  
3               8                  0                 1      0  
4               7                  0                 1      0

(166, 14)

In [3]:
labels=data['label']
labels.shape
labels.head()

(166,)

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

In [4]:
data=data[data.columns[:-1]]
data.head()
data.shape

Fever  Diarrhoea  Leftover concentrate  Leftover roughage  feedsource  \
0      0          0                     2                  2           0   
1      1          1                     0                  0           1   
2      0          0                     2                  2           2   
3      1          1                     0                  2           0   
4      1          1                     2                  2           0   

   Manger edge   WasteWaterdisposal  drain_lining  Dung disposal  Floor type  \
0            0                    0             1              1           3   
1            1                    1             0              1           0   
2            0                    1             2              1           4   
3            0                    0             0              0           0   
4            1                    0             0              0           4   

   Cleaning agent  Ventilation level   Housing system   
0               8                  2                 0  
1               8                  0                 2  
2               8                  0                 2  
3               8                  0                 1  
4               7                  0                 1

(166, 13)

In [5]:
from collections import Counter
counter_labels = Counter(labels)
print(counter_labels)

Counter({0: 70, 2: 52, 1: 44})


In [6]:
data.shape

(166, 13)

In [7]:
#Splitting data into training and testing
from sklearn.model_selection import train_test_split
#data=np.concatenate([relapse,no_relapse])
data.shape
X_train, X_test, y_train, y_test = train_test_split(data,labels, test_size=0.3,shuffle=True,random_state=23)

(166, 13)

In [8]:
X_train.shape
X_test.shape
len(y_train)
len(y_test)

(116, 13)

(50, 13)

116

50

In [9]:
counter_train = Counter(y_train)
print(counter_train)

Counter({0: 49, 2: 38, 1: 29})


In [10]:
counter_test = Counter(y_test)
print(counter_test)

Counter({0: 21, 1: 15, 2: 14})


## Generate model report

In [25]:
def generate_model_report(y_actual, y_predicted):
    print("Accuracy = " , accuracy_score(y_actual, y_predicted))
    print("Precision = " ,precision_score(y_actual, y_predicted, average=None))
    print("Recall = " ,recall_score(y_actual, y_predicted,average=None))
    print("F1 Score = " ,f1_score(y_actual, y_predicted,average=None))
    pass

In [30]:
def generate_auc_roc_curve(clf, X_test):
    y_pred_proba = clf.predict_proba(X_test)[:, 1]
    fpr, tpr, thresholds = roc_curve(y_test,  y_pred_proba)
    auc = roc_auc_score(y_test, y_pred_proba,average=None)
    plt.plot(fpr,tpr,label="AUC ROC Curve with Area Under the curve ="+str(auc))
    plt.legend(loc=4)
    plt.show()
    pass

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, confusion_matrix
from sklearn.metrics import f1_score, roc_auc_score, roc_curve

## NN


In [1]:
# from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
# from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt


clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=[8,4],random_state=27,early_stopping=True,verbose=True)
clf.fit(X_train,y_train)
pred=clf.predict(X_test)
generate_model_report(y_test, pred)
#     generate_auc_roc_curve(clf, X_test)
print(confusion_matrix(y_test,pred))
    
    
    
#Results


# Accuracy =  0.68
# Precision =  [0.78947368 0.66666667 0.53846154]
# Recall =  [0.71428571 0.8        0.5       ]
# F1 Score =  [0.75       0.72727273 0.51851852]
# [[15  3  3]
#  [ 0 12  3]
#  [ 4  3  7]]


KeyboardInterrupt: 